spring:
  datasource:
    url: jdbc:mysql://localhost:{MY_MYSQL_DB_PORT_NUMBER}/{MY_MYSQL_DB_SCHEMA_TITLE}?useSSL=false
    username: admin
    password: ${MY_MYSQL_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver